
version: "3.8"

services:
  minio:
    image: minio/minio
    command: server /data/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - minio-local
  server:
    container_name: server
    ports:
      - 8080:8080
    build: .
    environment:
      - MINIO_HOST=192.168.44.76
      - MINIO_PORT=9000
      - MINIO_USER=minioadmin
      - MINIO_PASSWORD=minioadmin
    networks:
      - minio-local


networks:
  minio-local:
    driver: bridge