
version: "3.8"

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
    depends_on:
      - minio
      - server
    networks:
      - minio-local
  minio:
    image: minio/minio
    command: server /data/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - minio-local
  server:
    container_name: server
    build: .
    environment:
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_USER=minioadmin
      - MINIO_PASSWORD=minioadmin
      - REMOTE_URL=192.168.44.76/minio-api
    networks:
      - minio-local


networks:
  minio-local:
    driver: bridge